# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=100)),
                ('pokemon_number', models.IntegerField()),
                ('expiration', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SightingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=64)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.Sighting')),
            ],
        ),
    ]
