# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20170917_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonzone',
            name='name',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
