# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_auto_20170923_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonzone',
            name='is_filter_blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='cp',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='iv',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
